# permissions for end users to edit williams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: william-editor-role
rules:
- apiGroups:
  - my.domain
  resources:
  - williams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - my.domain
  resources:
  - williams/status
  verbs:
  - get
