# permissions for end users to view williams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: william-viewer-role
rules:
- apiGroups:
  - my.domain
  resources:
  - williams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my.domain
  resources:
  - williams/status
  verbs:
  - get
